apiVersion: v1
kind: Secret
metadata:
  name: wxa4z-ingestion-credentials
  namespace: wxa4z-zad
type: Opaque
stringData:
  NATS_URL: "nats://wxa4z-nats.wxa4z-zad.svc.cluster.local:4222"
  NATS_PUBLIC_KEY: ""
  NATS_USER_SEED_KEY: ""
  NATS_JWT_TOKEN: ""
  NATS_SIGNING_SEED: ""
  NATS_OPERATOR_FINGERPRINT: ""
  INGESTION_API_KEY: ""