apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
  annotations:
    openshift.io/display-name: "NVIDIA GPU Operator"
    openshift.io/description: "Namespace for NVIDIA GPU Operator"
