# Tasks in this file are from documentation provided here:
# https://www.ibm.com/docs/en/software-hub/5.3.x?topic=piish-creating-secrets-services-that-use-multicloud-object-gateway

- name: Create MCG secrets for Software Hub components
  ansible.builtin.command: >
    cpd-cli manage setup-mcg
    --components={{ item }}
    --cpd_instance_ns={{ cpd_instance_ns }}
    --noobaa_account_secret={{ software_hub_noobaa_account_secret }}
    --noobaa_cert_secret={{ software_hub_noobaa_cert_secret }}
  loop: "{{ software_hub_mcg_components }}"
  register: mcg_result
  changed_when: false
  failed_when: "'The setup-mcg command ran successfully' not in mcg_result.stdout"
