# Tasks in this file are from documentation provided here:
# https://www.ibm.com/docs/en/software-hub/5.3.x?topic=piish-creating-secrets-services-that-use-multicloud-object-gateway

- name: Delete MCG secrets for Software Hub components
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: "{{ cpd_instance_ns }}"
    name: "{{ item.secret_name }}"
  loop:
    - { component: "watson_assistant", secret_name: "noobaa-account-watson-assistant" }
    - { component: "watson_assistant", secret_name: "noobaa-cert-watson-assistant" }
    - { component: "watson_assistant", secret_name: "noobaa-uri-watson-assistant" }
    - { component: "watsonx_orchestrate", secret_name: "noobaa-account-watsonx-orchestrate" }
    - { component: "watsonx_orchestrate", secret_name: "noobaa-cert-watsonx-orchestrate" }
    - { component: "watsonx_orchestrate", secret_name: "noobaa-uri-watsonx-orchestrate" }
  ignore_errors: true
