- name: Delete image pull secret from operator namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: "{{ cpd_operators_ns }}"
    name: "{{ software_hub_image_pull_secret }}"

- name: Delete image pull secret from instance namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: "{{ cpd_instance_ns }}"
    name: "{{ software_hub_image_pull_secret }}"