---
- name: Run install steps for wxa4z-v3.3 Operator
  tags:
    - install
    - operator
  block:

    - name: Create wxa4z-operator namespace
      kubernetes.core.k8s:
        state: present
        src: "{{ role_path }}/files/operator/wxa4z-namespace.yaml"

    - name: Create wxa4z Operator CatalogSource
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', role_path + '/templates/operator/wxa4z-catalog-source.yaml.j2') }}"

    - name: Wait for the WxA4Z CatalogSource to be ready
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: ibm-wxa4z-operator-catalog
        namespace: wxa4z-operator
      register: catalog_source_info
      until: >-
        catalog_source_info.resources | length > 0 and
        (catalog_source_info.resources[0].status is defined) and
        (catalog_source_info.resources[0].status.connectionState is defined) and
        (catalog_source_info.resources[0].status.connectionState.lastObservedState == 'READY')
      retries: 30
      delay: 10

    - name: Create wxa4z Operator Group (cluster-scoped)
      kubernetes.core.k8s:
        state: present
        src: "{{ role_path }}/files/operator/wxa4z-operator-group.yaml"

    - name: Create wxa4z Subscription
      kubernetes.core.k8s:
        state: present
        src: "{{ role_path }}/files/operator/wxa4z-subscription.yaml"

    - name: Wait for wxa4z operator deployment to be Available
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: ibm-wxa4z-operator-controller-manager
        namespace: wxa4z-operator
      register: wxa4z_operator_deploy
      until: >
        wxa4z_operator_deploy.resources | length > 0 and
        wxa4z_operator_deploy.resources[0].status.conditions is defined and
        (
          wxa4z_operator_deploy.resources[0].status.conditions
          | selectattr('type', 'equalto', 'Available')
          | selectattr('status', 'equalto', 'True')
          | list
          | length
        ) > 0
      retries: 60
      delay: 10